version: '3'
services:
  app:
    container_name: snack-api-service
    image: snack-api-service-postgresql
    build: ./
    ports:
      - "8080:8080"
    environment:
      DATABASE_HOST: dbpostgres
      DATABASE_PORT: 5432
      DATABASE_PASSWD: mysecretpassword
      DATABASE: postgres
      DATABASE_USER: postgres
      DATABASE_SCHEMA: snack_api
    depends_on:
      - dbpostgres
  dbpostgres:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres