spring:
  application:
    name: nutri-api-service
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE:postgres}?currentSchema=${DATABASE_SCHEMA:snack_api}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWD:mysecretpassword}
    platform: Posgresql
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          batch_size: 10
